# Generated by Django 5.2.8 on 2026-01-21 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('zone_geographique', models.CharField(max_length=100)),
                ('tarif_base', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('tarif_poids', models.FloatField()),
                ('tarif_volume', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_base', models.FloatField()),
                ('tarif_poids', models.FloatField()),
                ('tarif_volume', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.destination')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraison.typeservice')),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expedition', models.CharField(max_length=20, unique=True)),
                ('poids', models.FloatField()),
                ('volume', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('montant_total', models.FloatField(editable=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('Registered', 'Registered'), ('In transit', 'In transit'), ('Sorting', 'At sorting center'), ('Delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livraison.destination')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livraison.typeservice')),
            ],
        ),
    ]
