# Generated by Django 5.2.8 on 2026-01-23 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_etape', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(max_length=100)),
                ('statut_etape', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='livraison.expedition')),
            ],
        ),
    ]
