# Generated by Django 6.0 on 2026-01-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_suiviexpedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='tarif_forfaitaire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='tarif_poids',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='destination',
            name='tarif_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tarification',
            name='tarif_forfaitaire',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tarif_base',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_base',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_poids',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='tarif_poids',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='tarif_volume',
            field=models.FloatField(default=0.0),
        ),
    ]
