# Generated by Django 6.0 on 2026-01-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0003_destination_tarif_forfaitaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('Enregistré', 'Enregistré'), ('En transit', 'En transit'), ('Tri en cours', 'Centre de tri'), ('En livraison', 'En cours de livraison'), ('Livré', 'Livré'), ('Échec', 'Échec')], max_length=30),
        ),
    ]
