# Generated by Django 5.2.8 on 2026-01-21 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('permis', models.IntegerField()),
                ('telephone', models.CharField(max_length=50)),
                ('disponibilite', models.BooleanField(default=True)),
                ('date_embauche', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('capacite', models.FloatField()),
                ('etat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tournee', models.DateField()),
                ('kilometrage', models.FloatField(blank=True, null=True)),
                ('duree', models.DurationField(blank=True, null=True)),
                ('consommation_carburant', models.FloatField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.chauffeur')),
                ('expeditions', models.ManyToManyField(blank=True, to='livraison.expedition')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_incident', models.DateField()),
                ('gravite', models.CharField(max_length=50)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livraison.expedition')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.tournee')),
            ],
        ),
    ]
