# Generated by Django 6.0 on 2026-01-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_chauffeur_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='user',
        ),
        migrations.AddField(
            model_name='incident',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
