# Generated by Django 6.0 on 2026-01-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_remove_chauffeur_user_incident_is_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='is_resolved',
        ),
    ]
