# Generated by Django 5.2.8 on 2026-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_remove_incident_is_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='gravite',
            field=models.CharField(choices=[('Basse', 'Basse'), ('Moyenne', 'Moyenne'), ('Haute', 'Haute')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(choices=[('Delay', 'Retard'), ('Loss', 'Perte'), ('Damage', 'Endommagement'), ('Technical', 'Problème technique'), ('Other', 'Autre')], max_length=100),
        ),
    ]
