# Generated by Django 5.2.8 on 2026-01-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alter_incident_gravite_alter_incident_type_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='preuve',
            field=models.FileField(blank=True, null=True, upload_to='incidents/'),
        ),
    ]
