# Generated by Django 5.2.8 on 2026-01-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('livraison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='expeditions',
            field=models.ManyToManyField(to='livraison.expedition'),
        ),
    ]
