# Generated by Django 6.0 on 2026-01-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_facture_expeditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('CLIENT', 'Client'), ('CHAUFFEUR', 'Chauffeur')], default='', max_length=20),
        ),
    ]
