# Generated by Django 5.2.8 on 2026-01-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_client_user'),
        ('livraison', '0002_suiviexpedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reclamations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='expeditions',
            field=models.ManyToManyField(blank=True, to='livraison.expedition'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.facture'),
        ),
    ]
