# Generated by Django 6.0 on 2026-01-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_reclamation_assigned_to_reclamation_expeditions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='montant_HT',
            new_name='montant_ht',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='montant_TTC',
            new_name='montant_ttc',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='montant_TVA',
            new_name='montant_tva',
        ),
    ]
