# Generated by Django 6.0 on 2026-01-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_montant_ht_facture_montant_ht_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='montant_ht',
            new_name='montant_HT',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='montant_ttc',
            new_name='montant_TTC',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='montant_tva',
            new_name='montant_TVA',
        ),
    ]
